# Generated by Django 5.2.1 on 2025-05-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharanika', '0002_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('stream', models.CharField(max_length=50)),
            ],
        ),
    ]
