# Generated by Django 5.2.1 on 2025-05-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharanika', '0003_biodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
