# Generated by Django 5.2.1 on 2025-05-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharanika', '0004_alter_biodata_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='mobile_no',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
