# Generated by Django 5.2.1 on 2025-05-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharanika', '0005_alter_biodata_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
